server:
  port: 8083

spring:
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: empleado
          uri: lb://empleado
          predicates:
            - Path=/api/v1/empleado/**
          filters:
            - AutorizacionFilter
        - id: validarempleado
          uri: lb://validarempleado
          predicates:
            - Path=/api/v1/empleado-check/**
          filters:
            - AutorizacionFilter
        - id: autenticacion
          uri: lb://autenticacion
          predicates:
            - Path=/api/v1/autenticacion/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
#    enabled: false